name: geobase
description: Geospatial data (features, geometries, coordinates) writers (GeoJSON, WKT) for Dart. 
version: 0.1.0-a.0
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geobase

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
    
dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0
