name: geobase
description: Geospatial data structures, projections, tiling schemes and vector data support (GeoJSON, WKT, WKB). 
version: 0.3.2
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geobase

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.7.0
  proj4dart: ^2.0.0
      
dev_dependencies:
  test: ^1.21.1
  very_good_analysis: ^3.0.0
