name: geobase
description: Geospatial coordinates, projections, tiling schemes and data writers (GeoJSON, WKT) for Dart. 
version: 0.2.0
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geobase

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  proj4dart: ^2.0.0
      
dev_dependencies:
  test: ^1.21.1
  very_good_analysis: ^3.0.0
