name: geobase
description: Geospatial data, geometry, geodesy, projections, tiling schemes, and vector formats (GeoJSON, WKT, WKB). 
version: 1.5.0-dev.1
repository: https://github.com/navibyte/geospatial
homepage: https://geospatial.navibyte.dev/

topics:
  - location
  - utility
  - geojson
  - wgs84
  - map

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  meta: ^1.7.0
  proj4dart: ^2.0.0
      
dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
