name: geocore
description: Geospatial data structures (points, geometry, features, meta) and parsers (GeoJSON, WKT) for Dart. 
version: 0.10.0-dev.1
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geocore
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.7.0

  #geobase: ^0.3.0-dev.2
  geobase: 
    path: ../geobase

dev_dependencies:
  test: ^1.21.1
  very_good_analysis: ^3.0.0