name: geocore
description: Geospatial data structures and geometry classes for Dart.
version: 0.1.0-nullsafety.2
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geocore

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  equatable: ^2.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  
dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.12
