name: geocore
description: Geospatial data structures (features, geometry and metadata) and parsers (GeoJSON, WKT) for Dart. 
version: 0.8.0-pre.1
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geocore
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.3.0

  #attributes: ^0.8.0-pre.1
  attributes: 
    path: ../../../dataflow/dart/attributes
    
dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.3.0
  #lints: ^1.0.1