name: geocore
description: Geospatial data (points, geometry, features, meta) and parsers (GeoJSON, WKT) for Dart. 
version: 0.9.0-dev.0
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geocore

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  meta: ^1.8.0

  geobase: ^0.2.0-dev.5
  #geobase: 
  #  path: ../geobase

dev_dependencies:
  test: ^1.21.1
  very_good_analysis: ^3.0.0