name: geocore
description: Geospatial data structures (features, geometry and metadata) and utilities (GeoJSON, WKT) for Dart. 
version: 0.6.1
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geocore

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.3.0

  attributes: ^0.6.0
  # attributes: 
  #   path: ../../../dataflow/dart/attributes

dev_dependencies:
  test: ^1.16.4
