name: geocore
description: Geospatial data (points, geometry, features, meta), projections and parsers (GeoJSON, WKT) for Dart. 
version: 0.8.0-a.10
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geocore
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0
  proj4dart: ^2.0.0

  #geobase: ^0.1.0-a.1
  geobase: 
    path: ../geobase

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0