name: datatools
description: A library for Dart to help fetching data from HTTP and file resources and other data sources.
version: 0.5.0-nullsafety.0
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/datatools

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  equatable: ^2.0.0-nullsafety.0
  meta: ^1.3.0
  http: ^0.13.0
  http_parser: ^4.0.0
  path: ^1.8.0

  #meta: ^1.3.0-nullsafety.6
  #http: ^0.13.0-nullsafety.0
  #http_parser: ^4.0.0-nullsafety
  #path: ^1.8.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4

  #pedantic: ^1.10.0-nullsafety.3
  #test: ^1.16.0-nullsafety.12

