name: geodata
description: A geospatial client to read GeoJSON and other geospatial data sources.   
version: 0.8.0-a.4
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geodata
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3 
  meta: ^1.7.0
  synchronized: ^3.0.0

  datatools: ^0.8.0
  #datatools:
  #  path: ../../../dataflow/dart/datatools

  #geocore: ^0.8.0-a.4
  geocore: 
    path: ../geocore

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0
