name: geodata
description: A geospatial client to read GeoJSON and OGC API Features data sources.   
version: 1.4.0-dev.0
repository: https://github.com/navibyte/geospatial
homepage: https://geospatial.navibyte.dev/
publish_to: none

topics:
  - geojson
  - api
  - client
  - rest
  - openapi

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  #http: ^0.13.0
  http: any
  meta: ^1.7.0

  #geobase: ^1.1.0
  geobase: 
    path: ../geobase

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
