name: geodata
description: A geospatial client to read GeoJSON and OGC API Features data sources.   
version: 0.10.0-dev.0
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geodata
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  http: ^0.13.0
  meta: ^1.7.0

  #geobase: ^0.3.0-dev.0
  geobase: 
    path: ../geobase

  #geocore: ^0.10.0-dev.0
  geocore: 
    path: ../geocore

dev_dependencies:
  test: ^1.21.1
  very_good_analysis: ^3.0.0
