name: geodata
description: A geospatial client to read GeoJSON and other geospatial data sources.   
version: 0.7.0
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geodata

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.3.0
  synchronized: ^3.0.0

  attributes: ^0.7.1
  #attributes: 
  #  path: ../../../dataflow/dart/attributes

  datatools: ^0.7.0
  #datatools:
  #  path: ../../../dataflow/dart/datatools

  geocore: ^0.7.0
  #geocore: 
  #  path: ../geocore

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.4
