name: geodata
description: A geospatial client to read GeoJSON and OGC API Features data sources.   
version: 0.12.0-dev.0
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geodata

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  equatable: ^2.0.0
  http: ^0.13.0
  meta: ^1.7.0

  geobase: ^0.5.0-dev.1
  #geobase: 
  #  path: ../geobase

dev_dependencies:
  test: ^1.21.1
  very_good_analysis: ^5.0.0
