name: geodata
description: A geospatial client to read GeoJSON and OGC API Features data sources.   
version: 0.8.0-a.8
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geodata

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3 
  http: ^0.13.4
  meta: ^1.7.0
  
  #synchronized: ^3.0.0

  geocore: ^0.8.0-a.7
  #geocore: 
  #  path: ../geocore

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0
