name: geodata
description: A geospatial client to read GeoJSON and OGC API Features data sources.   
version: 0.8.0-a.10
repository: https://github.com/navibyte/geospatial
homepage: https://github.com/navibyte/geospatial/tree/main/dart/geodata
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  equatable: ^2.0.3 
  http: ^0.13.4
  meta: ^1.7.0
  
  #synchronized: ^3.0.0

  #geobase: ^0.1.0-a.1
  geobase: 
    path: ../geobase

  #geocore: ^0.8.0-a.10
  geocore: 
    path: ../geocore

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0
